### ISSUE TITLE
More detail about the number of address.

### ISSUE THREAD

**Issue by oopsmonk** [Hribek25/IOTA101#5]
In theory, the address has 81 trytes, and 1 tryte has 27 combinations, one seed can have (27^81) addresses.  
The address number is (2^53-1) in Javascript and (2^63-1) in Python on a 64-bit platform.
http://iota101.info/Allchapters_python.ipynb.html#Seed,-private-key-and-address

**Comment by Hribek25** [comment]
Thank you for your feedback.

So probably we should stick to (2^53-1) since the address range should be reachable regardless programming language, right? What do you think?

**Comment by oopsmonk** [comment]
since your talking about python, you might wanna use (2^63-1).
